### ISSUE TITLE
Modificar el dashboard para que se puedan visualizar, subir y eliminar imagenes 

### ISSUE THREAD

**Issue by IguanaBanana** [IguanaBanana/aplicacioneswebI4.0#3]

**Comment by Jteran92** [comment]
https://github.com/IguanaBanana/aplicacioneswebI4.0/pull/21

**Comment by ivanchenoweth** [comment]
Estea historia/issue Esta incompleta en su descripcion y seteo,
sin rama, sin etiqueta, sin milesstone, sin fechas, etc.
