### ISSUE TITLE
Hacer el diseño de la pagina configuracion 

### ISSUE THREAD

**Issue by IguanaBanana** [IguanaBanana/aplicacioneswebI4.0#8]

**Comment by ivanchenoweth** [comment]
Agreguen al menos una etiqueta, y el proyecto

**Comment by ivanchenoweth** [comment]
En que rama esta esto?

**Comment by DanSaurio** [comment]
Se modifico el diseño de la pagina configuracion(y los demas tambien, el diseño base) y se incorporo la configuracion para recibir el cambio de contraseña mediante correo

**Comment by ivanchenoweth** [comment]
Agregar el mockup o el screenshot ya terminado ...
